spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: swagger-api
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
