---
info:
  component: Default Single Swagger Document Server for MicroService

spring:
  profiles: default

server:
  port: 8014
  servlet:
    contextPath: /api/swagger-api

documentation: 
  baseurl: ${BASE_URI}
  swagger: 
    services: 
      -    
        name: amq-api
        url: ${documentation.baseurl}/amq/swagger
        version: 2.0    
      -
        name: asociados
        url: ${documentation.baseurl}/asociados/v2/api-docs
        version: 2.0
      - 
        name: comision-venta-api
        url: ${documentation.baseurl}/comisiones-ventas/v2/api-docs
        version: 2.0
      - 
        name: commons-api
        url: ${documentation.baseurl}/commons/v2/api-docs
        version: 2.0
      -    
        name: engage-integracion-api
        url: ${documentation.baseurl}/engageIntegracion/v2/api-docs
        version: 2.0
      - 
        name:  empresa-api
        url: ${documentation.baseurl}/empresas/v2/api-docs
        version: 2.0
      - 
        name: grupoFamiliar
        url: ${documentation.baseurl}/grupoFamiliar/v2/api-docs
        version: 2.0
      -
        name:  obra-social-api
        url: ${documentation.baseurl}/obrasSociales/v2/api-docs
        version: 2.0
      - 
        name:  payment-manager-api
        url: ${documentation.baseurl}/responsablePagoApi/v2/api-docs
        version: 2.0
      - 
        name:  presupuesto-api
        url: ${documentation.baseurl}/presupuestos/v2/api-docs
        version: 2.0
      -    
        name: rhpam-api
        url: ${documentation.baseurl}/rhpam/swagger
        version: 2.0
      - 
        name: valorizacion-api
        url: ${documentation.baseurl}/valorizacion/v2/api-docs
        version: 2.0
    