apiVersion: v1
kind: Template
metadata:
  name: swagger-api
  annotations:
    openshift.io/display-name: SUME Utilidades API
    iconClass: fa fa-code
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: java:8
          namespace: openshift
      type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - image: ${APP_NAME}:latest
          name: swagger-api
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /commons/actuator/health
          #     port: 8014
          #     scheme: HTTP
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /commons/actuator/health
          #     port: 8014
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 180
          #   successThreshold: 1
          #   timeoutSeconds: 1
          ports:
          - containerPort: 8014
            protocol: TCP
    triggers: 
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APP_NAME}
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: 8014-tcp
      port: 8014
      protocol: TCP
      targetPort: 8014
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: 8014-tcp
    to:
      kind: Service
      name: ${APP_NAME}
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: hello-service
- description: Git Repository
  displayName: Git Repository
  name: GIT_REPO
  required: true
  value: https://ASEConecta@dev.azure.com/ASEConecta/SIGO/_git/utilidades-api
- description: Git Branch
  displayName: Git Branch
  name: GIT_BRANCH
  required: true
  value: master
